### ISSUE TITLE
Tanya

### ISSUE THREAD

**Issue by amik99** [muhammadridhot/kantin-MIKAN-Administrator#1]
Aplikasi ini cara penggunaannya gmn yah mas ... terima kasih mas

**Comment by mridhot** [comment]
> Aplikasi ini cara penggunaannya gmn yah mas ... terima kasih mas

ini web uda admin nya, yang mengelola data2 seperti daftar transaksi, top up, dll

**Comment by amik99** [comment]
Iya mas soalnya tadi aq cba pakai node.js gagal trs ... maaf mas banyak tanya

**Comment by mridhot** [comment]
> Iya mas soalnya tadi aq cba pakai node.js gagal trs ... maaf mas banyak tanya

kebetulan database nya pakai firebase, jadi perlu di sett key firebasenya

**Comment by amik99** [comment]
Ok2 mas terima kasih ...

**Comment by mridhot** [comment]
> Ok2 mas terima kasih ...

sep, code ini uda cukup lama dan perlu ditingkatkan menjadi lebih baik lagi, semoga bisa di up lagi ya, Good Luck

**Comment by amik99** [comment]
Klo masnya yg tingkatkan seh sippzz banget ... kalau aq ampun mas soalnya rencana cuma mau saya aplikasikan dikantin sekolah saja mas

**Comment by mridhot** [comment]
> Klo masnya yg tingkatkan seh sippzz banget ... kalau aq ampun mas soalnya rencana cuma mau saya aplikasikan dikantin sekolah saja mas

lagi sibuk dengan pekerjaan sih, mungkin kalau ada waktu saya up lagi dan semoga bermanfaat

**Comment by amik99** [comment]
Amiin ... sukses selalu mas
